"""SQLAlchemy model for dbgpt_serve_scheduled_run."""

from sqlalchemy import Column, DateTime, Integer, String, Text

from dbgpt.storage.metadata import Model


class ScheduledRunEntity(Model):
    """Scheduled task execution history (run records for each task trigger)."""

    __tablename__ = "dbgpt_serve_scheduled_run"

    id = Column(
        Integer, primary_key=True, autoincrement=True, comment="Auto increment id"
    )
    run_id = Column(String(64), unique=True, nullable=False, comment="Run UUID")
    task_id = Column(
        String(64), nullable=False, index=True, comment="Associated task UUID"
    )
    started_at = Column(DateTime, nullable=False, index=True, comment="Run start time")
    finished_at = Column(DateTime, nullable=True, comment="Run finish time")
    status = Column(
        String(32),
        nullable=False,
        comment="Run status: running / success / failed / timeout",
    )
    result_summary = Column(Text, nullable=True, comment="Result summary")
    error_message = Column(Text, nullable=True, comment="Error message if failed")
    output_conv_uid = Column(
        String(64),
        nullable=True,
        comment="Output conversation UID generated by this run",
    )

    def __repr__(self) -> str:
        return (
            f"ScheduledRunEntity(run_id='{self.run_id}', "
            f"task_id='{self.task_id}', status='{self.status}')"
        )
