# -*- encoding:utf-8 -*-
'''
@describe:
@author: Li Anbang
@Create
Date: 2024 / 1 / 11
下午1: 44
'''
import json

first_departments = [
    {'parent_org': '', 'shortname': 'SLS', 'fullname': 'Sales', 'chinesename': '销售部'},
    {'parent_org': '', 'shortname': 'CPD', 'fullname': 'Cell Product Design', 'chinesename': '电芯产品设计部'},
    {'parent_org': '', 'shortname': 'PMD', 'fullname': 'Product Management Department', 'chinesename': '产品管理部'},
    {'parent_org': '', 'shortname': 'TPM', 'fullname': 'Tech.Project Management', 'chinesename': '项目技术部'},
    {'parent_org': '', 'shortname': 'PRJ', 'fullname': 'Project Engineering', 'chinesename': '项目工程部'},
    {'parent_org': '', 'shortname': 'CL', 'fullname': 'Central Lab', 'chinesename': '中心实验室'},
    {'parent_org': '', 'shortname': 'RI', 'fullname': 'Research Institute', 'chinesename': '研究院'},
    {'parent_org': '', 'shortname': 'APD', 'fullname': 'Advanced Product Development', 'chinesename': '先进产品开发部'},
    {'parent_org': '', 'shortname': 'MRD', 'fullname': 'Manufacturing Research & Development', 'chinesename': '制造研发部'},
    {'parent_org': '', 'shortname': 'IP', 'fullname': 'Intellectual Property', 'chinesename': '知识产权部'},
    {'parent_org': '', 'shortname': 'MU-SSL', 'fullname': 'Manufacturing Unit-SSL	松湖园-', 'chinesename': 'S区'},
    {'parent_org': '', 'shortname': 'MU Plus', 'fullname': 'MU Plus', 'chinesename': '智能制造特区'},
    {'parent_org': '', 'shortname': 'PRD', 'fullname': 'Production Department', 'chinesename': '生产部'},
    {'parent_org': '', 'shortname': 'ME', 'fullname': 'Manufacturing Engineering', 'chinesename': '制造工程部'},
    {'parent_org': '', 'shortname': 'PTO', 'fullname': 'Prototype Department', 'chinesename': '样品制造部'},
    {'parent_org': '', 'shortname': 'xTW', 'fullname': 'NICT Cell Operational Team	NICT', 'chinesename': '电芯运营专区'},
    {'parent_org': '', 'shortname': 'IE', 'fullname': 'Industrial Engineering', 'chinesename': '工业工程部'},
    {'parent_org': '', 'shortname': 'LOG', 'fullname': 'Logistics', 'chinesename': '物流部'},
    {'parent_org': '', 'shortname': 'PMC', 'fullname': 'Plan & Material Control', 'chinesename': '计划与物料控制部'},
    {'parent_org': '', 'shortname': 'SRC', 'fullname': 'Sourcing', 'chinesename': '资材部'},
    {'parent_org': '', 'shortname': 'QA', 'fullname': 'Quality Assurance', 'chinesename': '品质保证部'},
    {'parent_org': '', 'shortname': 'CPP', 'fullname': 'Corporate Planning', 'chinesename': '企业策划部'},
    {'parent_org': '', 'shortname': 'LA', 'fullname': 'Legal Affairs', 'chinesename': '法务部'},
    {'parent_org': '', 'shortname': 'IDT', 'fullname': 'Information Digital Technology',  'chinesename': '信息数字化技术部'},
    {'parent_org': '', 'shortname': 'PSO', 'fullname': 'President Supporting Office', 'chinesename': '总裁办公室'},
    {'parent_org': '', 'shortname': 'FNC', 'fullname': 'Finance', 'chinesename': '财务部'},
    {'parent_org': '', 'shortname': 'HR', 'fullname': 'Human Resources', 'chinesename': '人力资源部'},
    {'parent_org': '', 'shortname': 'FE', 'fullname': 'Facility Engineering', 'chinesename': '厂房工程部'},
    {'parent_org': '', 'shortname': 'ES', 'fullname': 'Employee Service', 'chinesename': '雇员服务部'},
    {'parent_org': '', 'shortname': 'PA', 'fullname': 'Public Affairs', 'chinesename': '外联部'},
    {'parent_org': '', 'shortname': 'SD', 'fullname': 'Sustainable Development Department',   'chinesename': '可持续发展部'},
    {'parent_org': '', 'shortname': 'SEC', 'fullname': 'Security', 'chinesename': '保安部'}]

second_departments = [
    {'parent_org': 'SLS', 'shortname': 'BO/CS', 'fullname': 'Back office/Customer Service',
     'chinesename': '销售支持/客服'},
    {'parent_org': 'SLS', 'shortname': 'NCT', 'fullname': 'Non Consumer Team', 'chinesename': '非消费类'},
    {'parent_org': 'SLS', 'shortname': 'AP1A', 'fullname': 'Asia Pacific1-1', 'chinesename': '亚太区1A'},
    {'parent_org': 'SLS', 'shortname': 'EU', 'fullname': 'Europe', 'chinesename': '欧洲业务'},
    {'parent_org': 'SLS', 'shortname': 'AP1B', 'fullname': 'Asia Pacific1-2', 'chinesename': '亚太区1B'},
    {'parent_org': 'SLS', 'shortname': 'AP2', 'fullname': 'Asia Pacific2', 'chinesename': '亚太区2'},
    {'parent_org': 'SLS', 'shortname': 'AP3', 'fullname': 'Asia Pacific3', 'chinesename': '亚太区3'},
    {'parent_org': 'SLS', 'shortname': 'AP4', 'fullname': 'Asia Pacific4', 'chinesename': '亚太区4'},
    {'parent_org': 'SLS', 'shortname': 'K1', 'fullname': 'Key Account1', 'chinesename': '关键客户1'},
    {'parent_org': 'SLS', 'shortname': 'U1', 'fullname': 'U.S.A.1', 'chinesename': '美国区1'},
    {'parent_org': 'CPD', 'shortname': 'CMO', 'fullname': 'CPD Management Office', 'chinesename': 'CPD管理办公室'},
    {'parent_org': 'CPD', 'shortname': 'CDC', 'fullname': 'Cell Design Center', 'chinesename': '产品设计中心'},
    {'parent_org': 'CPD', 'shortname': 'PCPL', 'fullname': 'PC Product Line', 'chinesename': '电脑平台开发部'},
    {'parent_org': 'CPD', 'shortname': 'PPL', 'fullname': 'Phone Product Line', 'chinesename': '手机平台开发部'},
    {'parent_org': 'CPD', 'shortname': 'EAP', 'fullname': 'Elite Account Portfolio', 'chinesename': 'E客户项目群'},
    {'parent_org': 'CPD', 'shortname': 'SAP', 'fullname': 'Strategic Account Portfolio', 'chinesename': 'S客户项目群'},
    {'parent_org': 'CPD', 'shortname': 'CAP', 'fullname': 'Competitive Account Portfolio',
     'chinesename': 'C客户项目群'},
    {'parent_org': 'CPD', 'shortname': 'PAP', 'fullname': 'PAP - PLT and NPI Development',
     'chinesename': 'A客户项目部'},
    {'parent_org': 'PMD', 'shortname': 'PPD', 'fullname': 'Product Planning Department', 'chinesename': '产品规划部'},
    {'parent_org': 'PMD', 'shortname': 'MKT', 'fullname': 'Marketing', 'chinesename': '市场部'},
    {'parent_org': 'TPM', 'shortname': 'TPM1', 'fullname': 'TPM1', 'chinesename': '项目技术部一组'},
    {'parent_org': 'TPM', 'shortname': 'TPM2', 'fullname': 'TPM2', 'chinesename': '项目技术部二组'},
    {'parent_org': 'TPM', 'shortname': 'TPM4', 'fullname': 'TPM4', 'chinesename': '项目技术部四组'},
    {'parent_org': 'CL', 'shortname': 'ND-Lab', 'fullname': 'ND-Lab', 'chinesename': '宁德实验室'},
    {'parent_org': 'CL', 'shortname': 'DG-Lab', 'fullname': 'DG-Lab', 'chinesename': '东莞实验室'},
    {'parent_org': 'CL', 'shortname': 'MTS', 'fullname': 'Multi Technology Simulation', 'chinesename': '仿真部'},
    {'parent_org': 'RI', 'shortname': 'CT', 'fullname': 'Cathode', 'chinesename': '正极材料研发部'},
    {'parent_org': 'RI', 'shortname': 'AN', 'fullname': 'Anode', 'chinesename': '负极材料研发部'},
    {'parent_org': 'RI', 'shortname': 'EL', 'fullname': 'Electrolyte', 'chinesename': '电解液研发部'},
    {'parent_org': 'RI', 'shortname': '00:01Lab', 'fullname': '00:01 Laboratory', 'chinesename': '零点零壹实验室'},
    {'parent_org': 'RI', 'shortname': 'RCM', 'fullname': 'Research cooperation Management',
     'chinesename': '研发管理部'},
    {'parent_org': 'RI', 'shortname': 'ACE', 'fullname': 'Advanced Chemistry Exploration',
     'chinesename': '先进化学体系探索部'},
    {'parent_org': 'APD', 'shortname': 'FIT', 'fullname': 'Frontier Initiative Technology',
     'chinesename': '化学体系创新部'},
    {'parent_org': 'APD', 'shortname': 'AIT', 'fullname': 'Architecture Initiative Technology',
     'chinesename': '产品结构创新部'},
    {'parent_org': 'APD', 'shortname': 'AMO', 'fullname': 'APD Management Office', 'chinesename': 'APD管理办公室'},
    {'parent_org': 'MRD', 'shortname': 'EET', 'fullname': 'Electrode Engineering Team', 'chinesename': '极片工程部'},
    {'parent_org': 'MRD', 'shortname': 'ADT', 'fullname': 'Assembly Development Team', 'chinesename': '组装开发部'},
    {'parent_org': 'MRD', 'shortname': 'PDT', 'fullname': 'Platform Development Team', 'chinesename': '平台开发部'},
    {'parent_org': 'MRD', 'shortname': 'AMD', 'fullname': 'Advanced Manufacturing Development',
     'chinesename': '先进制造部'},
    {'parent_org': 'PRJ', 'shortname': 'PRJ-DG', 'fullname': 'Dong Guan Project', 'chinesename': 'DG项目部'},
    {'parent_org': 'PRJ', 'shortname': 'PRJ-NDPAP', 'fullname': 'PRJ-NDPAP', 'chinesename': 'PRJ-ND A客户项目部'},
    {'parent_org': 'PRJ', 'shortname': 'PRJ-NDSAP1', 'fullname': 'PRJ-ND Strategic Account Portfolio1',
     'chinesename': 'PRJ-ND S客户项目1部'},
    {'parent_org': 'PRJ', 'shortname': 'PRJ-NDSAP2', 'fullname': 'PRJ-ND Strategic Account Portfolio2',
     'chinesename': 'PRJ-ND S客户项目2部'},
    {'parent_org': 'PRJ', 'shortname': 'MIC', 'fullname': 'Manufacture Improvement Center',
     'chinesename': '制造改善部'},
    {'parent_org': 'MU-SSL', 'shortname': 'SSL-PRD', 'fullname': 'SSL-Production', 'chinesename': 'SSL生产部'},
    {'parent_org': 'MU-SSL', 'shortname': 'SSL-ME', 'fullname': 'SSL-Maintenance Engineering',
     'chinesename': 'SSL设备技术部'},
    {'parent_org': 'MU-SSL', 'shortname': 'SSL-PTO/EP', 'fullname': '', 'chinesename': 'SSL样品/前工序'},
    {'parent_org': 'MU Plus', 'shortname': 'MU Plus Operation', 'fullname': 'Manufacturing Unit Plus Operation',
     'chinesename': '智能制造特区运营部'},
    {'parent_org': 'MU', 'shortname': 'MU Plus Digi-Lean', 'fullname': 'Manufacturing Unit Plus Digi Lean',
     'chinesename': '智能制造特区Digi-Lean部'},
    {'parent_org': 'PRD', 'shortname': 'PRD-ND1', 'fullname': 'Production Department-ND1', 'chinesename': 'ND生产1部'},
    {'parent_org': 'PRD', 'shortname': 'PRD-ND2', 'fullname': 'Production Department-ND2', 'chinesename': 'ND生产2部'},
    {'parent_org': 'PRD', 'shortname': 'PRD-MC&TC', 'fullname': 'Management Center & Training Center',
     'chinesename': '公共业务组'},
    {'parent_org': 'ME', 'shortname': 'ME-EP', 'fullname': 'Electrode Production', 'chinesename': '极片制造工程部'},
    {'parent_org': 'ME', 'shortname': 'ME-ND1', 'fullname': 'ME-ND1', 'chinesename': 'ND制造工程部1'},
    {'parent_org': 'ME', 'shortname': 'ME-ND2', 'fullname': 'ME-ND2', 'chinesename': 'ND制造工程部2'},
    {'parent_org': 'ME', 'shortname': 'ME-TC', 'fullname': 'ME Technical Center', 'chinesename': 'ME技术中心'},
    {'parent_org': 'PTO', 'shortname': 'PTO-PRD', 'fullname': 'Prototype Production',
     'chinesename': '样品制造部-生产部'},
    {'parent_org': 'PTO', 'shortname': 'PTO-ME', 'fullname': 'Prototype Machine Engineering',
     'chinesename': '样品制造部-设备技术部'},
    {'parent_org': 'PTO', 'shortname': 'PTO-Lab', 'fullname': 'Prototype Laboratory',
     'chinesename': '样品制造部-电芯测试部'},
    {'parent_org': 'xTW', 'shortname': 'xTW-EP-PRD', 'fullname': 'xTW Electrode Production Department',
     'chinesename': 'xTW前工序生产部'},
    {'parent_org': 'xTW', 'shortname': 'xTW-EP-ME', 'fullname': 'xTW Electrode Maintenance Engineering',
     'chinesename': 'xTW前工序设备技术部'},
    {'parent_org': 'xTW', 'shortname': 'xTW-EP-PE', 'fullname': 'xTW Electrode Process Engineering',
     'chinesename': 'xTW前工序工艺工程部'},
    {'parent_org': 'xTW', 'shortname': 'xTW-ASSY-PRD21', 'fullname': 'xTW Assembly Production Department-21',
     'chinesename': 'xTW后工序生产部-21'},
    {'parent_org': 'xTW', 'shortname': 'xTW-ASSY-ME21', 'fullname': 'xTW Assembly Maintenance Engineering-21',
     'chinesename': 'xTW后工序设备技术部-21'},
    {'parent_org': 'xTW', 'shortname': 'xTW-ASSY-PE21', 'fullname': 'xTW Assembly Process Engineering-21',
     'chinesename': 'xTW后工序工艺工程部-21'},
    {'parent_org': 'xTW', 'shortname': 'xTW-ASSY-PRD22', 'fullname': 'xTW Assembly Production Department-22',
     'chinesename': 'xTW后工序生产部-22'},
    {'parent_org': 'xTW', 'shortname': 'xTW-ASSY-ME22', 'fullname': 'xTW Assembly Maintenance Engineering-22',
     'chinesename': 'xTW后工序设备技术部-22'},
    {'parent_org': 'xTW', 'shortname': 'xTW-ASSY-PE22', 'fullname': 'xTW Assembly Process Engineering-22',
     'chinesename': 'xTW后工序工艺工程部-22'},
    {'parent_org': 'PMC', 'shortname': 'PMC-MPS', 'fullname': 'Master Plan & System', 'chinesename': '主计划&系统组'},
    {'parent_org': 'PMC', 'shortname': 'PMC-PC', 'fullname': 'PMC-Plan Control', 'chinesename': '计划控制组'},
    {'parent_org': 'IE', 'shortname': 'NPI', 'fullname': 'New Product Introduction', 'chinesename': '新产品导入组'},
    {'parent_org': 'IE', 'shortname': 'RP', 'fullname': 'Resources Planning', 'chinesename': '资源规划组'},
    {'parent_org': 'IE', 'shortname': 'CI', 'fullname': 'Cost Improvement', 'chinesename': '成本改善组'},
    {'parent_org': 'IE', 'shortname': 'NP', 'fullname': 'Non-production Planning', 'chinesename': '非生产规划组'},
    {'parent_org': 'LOG', 'shortname': 'LOG-DG', 'fullname': 'Logistics-DG', 'chinesename': '东莞物流部'},
    {'parent_org': 'LOG', 'shortname': 'LOG-ND', 'fullname': 'Logistics-ND', 'chinesename': '宁德物流部'},
    {'parent_org': 'LOG', 'shortname': 'LOG-HK', 'fullname': 'Logistics-HK', 'chinesename': '香港物流部'},
    {'parent_org': 'SRC', 'shortname': 'DMP', 'fullname': 'Direct Material Procurement',
     'chinesename': '直接生产物料采购部'},
    {'parent_org': 'SRC', 'shortname': 'NPP', 'fullname': 'Non-production Procurement',
     'chinesename': '间接物料采购部'},
    {'parent_org': 'SRC', 'shortname': 'PCO', 'fullname': 'Procurement Control Office',
     'chinesename': '采购控制&管理办公室'},
    {'parent_org': 'SRC', 'shortname': 'ATLI-SRC', 'fullname': 'ATLI-Sourcing', 'chinesename': 'ATLI-资材部'},
    {'parent_org': 'QA', 'shortname': 'SQM', 'fullname': 'Supplier Quality Management',
     'chinesename': '供应商质量管理部'},
    {'parent_org': 'QA', 'shortname': 'QE', 'fullname': 'Quality Engineering', 'chinesename': '质量工程部'},
    {'parent_org': 'QA', 'shortname': 'QMC', 'fullname': 'Quality Management Center', 'chinesename': '质量管理中心'},
    {'parent_org': 'QA', 'shortname': 'RSE', 'fullname': 'Reliability  Safety Engineering',
     'chinesename': '安全可靠性工程部'},
    {'parent_org': 'CPP', 'shortname': 'ATG', 'fullname': 'Advanced Technology Investment',
     'chinesename': '先进技术投资组'},
    {'parent_org': 'CPP', 'shortname': 'IMG', 'fullname': 'Investment Management', 'chinesename': '投资管理组'},
    {'parent_org': 'CPP', 'shortname': 'CDG', 'fullname': '"Corporate Development & Governance "',
     'chinesename': '企业发展与管控组'},
    {'parent_org': 'IDT', 'shortname': 'IDT-MO', 'fullname': 'IDT-Management Office', 'chinesename': 'IDT管理办公室'},
    {'parent_org': 'IDT', 'shortname': 'BP-RD', 'fullname': 'Business Partner-RD', 'chinesename': '研发解决方案部'},
    {'parent_org': 'IDT', 'shortname': 'BP-SCM', 'fullname': 'Business Partner-SCM', 'chinesename': '供应链解决方案部'},
    {'parent_org': 'IDT', 'shortname': 'BP-MU', 'fullname': 'Business Partner-MU', 'chinesename': '制造解决方案部'},
    {'parent_org': 'IDT', 'shortname': 'AI', 'fullname': 'Industrial Artificial Intelligence',
     'chinesename': '工业智能部'},
    {'parent_org': 'IDT', 'shortname': 'DP', 'fullname': 'Data Platform', 'chinesename': '数据平台部'},
    {'parent_org': 'IDT', 'shortname': 'AD', 'fullname': 'Application Development', 'chinesename': '技术开发部'},
    {'parent_org': 'IDT', 'shortname': 'CS', 'fullname': 'Client Service', 'chinesename': '桌面服务部'},
    {'parent_org': 'IDT', 'shortname': 'IS', 'fullname': 'Infrastructure Service', 'chinesename': '基础设施服务部'},
    {'parent_org': 'PSO', 'shortname': 'STE', 'fullname': 'Strategy To Execution', 'chinesename': '战略执行组'},
    {'parent_org': 'PSO', 'shortname': 'CCT', 'fullname': 'Corporate Culture/Communication Team',
     'chinesename': '企业文化组'},
    {'parent_org': 'PSO', 'shortname': 'CPA', 'fullname': 'Corporate public affairs', 'chinesename': '企业公共事务部'},
    {'parent_org': 'FNC', 'shortname': 'FSSC', 'fullname': 'Financial Shared Service Center',
     'chinesename': '账务共享中心'},
    {'parent_org': 'FNC', 'shortname': 'COE', 'fullname': 'Center of Excellent', 'chinesename': '专业财务中心'},
    {'parent_org': 'FNC', 'shortname': 'OMO', 'fullname': 'Operation management office', 'chinesename': '经营管理部'},
    {'parent_org': 'FNC', 'shortname': 'RC', 'fullname': 'Reporting center', 'chinesename': '报告中心'},
    {'parent_org': 'FNC', 'shortname': 'ATLS-FNC', 'fullname': 'ATL Singapore-FNC', 'chinesename': '新加坡财务部'},
    {'parent_org': 'HR', 'shortname': 'TR', 'fullname': 'Total Rewards', 'chinesename': '薪酬与激励部'},
    {'parent_org': 'HR', 'shortname': 'TA', 'fullname': 'Talent Acquisition', 'chinesename': '人才招聘与调配部'},
    {'parent_org': 'HR', 'shortname': 'O&TD', 'fullname': 'Organization&Talent Development',
     'chinesename': '组织与人才发展部'},
    {'parent_org': 'HR', 'shortname': 'OPS', 'fullname': 'Operation Center', 'chinesename': '运营中心'},
    {'parent_org': 'HR', 'shortname': 'OM', 'fullname': 'Oversea Management', 'chinesename': '海外管理部'},
    {'parent_org': 'FE', 'shortname': 'FOM', 'fullname': 'Facility Operation Maintenance', 'chinesename': '运维组'},
    {'parent_org': 'FE', 'shortname': 'SYS', 'fullname': 'System', 'chinesename': '系统组'},
    {'parent_org': 'FE', 'shortname': 'Tech', 'fullname': 'Technology Management', 'chinesename': '技管组'},
    {'parent_org': 'ES', 'shortname': 'ES-DG', 'fullname': 'Employee Service-DG', 'chinesename': '东莞雇员服务部'},
    {'parent_org': 'ES', 'shortname': 'ES-ND', 'fullname': 'Employee Service-ND', 'chinesename': '宁德雇员服务部'},
    {'parent_org': 'SD', 'shortname': 'EHS-DG', 'fullname': 'Environment,Health and Safety Management(DG)',
     'chinesename': 'EHS-DG管理组'},
    {'parent_org': 'SD', 'shortname': 'BCM', 'fullname': 'Business Continuity Management(Group)',
     'chinesename': 'BCM管理组(集团)'},
    {'parent_org': 'SD', 'shortname': 'EHS-ND', 'fullname': 'Environment,Health and Safety Management(ND)',
     'chinesename': 'EHS-ND管理组'},
    {'parent_org': 'SD', 'shortname': 'EHS Tech', 'fullname': 'Environment,Health and Safety Technology(Group)',
     'chinesename': 'EHS技术组(集团)'},
    {'parent_org': 'SD', 'shortname': 'CSR&EHS Sys', 'fullname': 'Corporate Social Responsibility & EHS System(Group)',
     'chinesename': '企业社会责任&EHS体系组(集团)'},
]
third_departments = [
    {'parent_org': 'EAP', 'shortname': 'H&H', 'fullname': 'Huawei&HONOR', 'chinesename': 'HUA & HOR组'},
    {'parent_org': 'EAP', 'shortname': 'OPO', 'fullname': 'OPO', 'chinesename': 'OPO组'},
    {'parent_org': 'EAP', 'shortname': 'VVO', 'fullname': 'ViVO', 'chinesename': 'VVO组'},
    {'parent_org': 'EAP', 'shortname': 'MIX', 'fullname': 'Xiaomi', 'chinesename': 'MIX组'},
    {'parent_org': 'SAP', 'shortname': 'SAP1', 'fullname': 'SAP1', 'chinesename': 'SAP1组'},
    {'parent_org': 'SAP', 'shortname': 'SAP3', 'fullname': 'SAP3', 'chinesename': 'SAP3组'},
    {'parent_org': 'SAP', 'shortname': 'SAP4', 'fullname': 'SAP4', 'chinesename': 'SAP4组'},
    {'parent_org': 'PAP', 'shortname': 'PAP1', 'fullname': 'PAP1', 'chinesename': 'PAP1组'},
    {'parent_org': 'PAP', 'shortname': 'PAP2', 'fullname': 'PAP2', 'chinesename': 'PAP2组'},
    {'parent_org': 'PAP', 'shortname': 'PAP3', 'fullname': 'PAP3', 'chinesename': 'PAP3组'},
    {'parent_org': 'PPD', 'shortname': 'PPT', 'fullname': 'Product Planning Team', 'chinesename': '需求管理部'},
    {'parent_org': 'PPD', 'shortname': 'CMA', 'fullname': 'Competition Management & Analysis Team',
     'chinesename': '竞争管理部'},
    {'parent_org': 'ND-Lab', 'shortname': 'BTL-MDA', 'fullname': 'Battery Test Lab-Method Development & Application',
     'chinesename': '电芯测试技术开发与应用组'},
    {'parent_org': 'ND-Lab', 'shortname': 'MAL-MDA',
     'fullname': 'Material Analysis Lab-Method Development & Application', 'chinesename': '材料表征方法开发与应用组'},
    {'parent_org': 'ND-Lab', 'shortname': 'EMG', 'fullname': 'Eletrochemical Mechanism Group',
     'chinesename': '电化学机理组'},
    {'parent_org': 'DG-Lab', 'shortname': 'BTL', 'fullname': 'Battery Test Lab', 'chinesename': '电池测试实验室'},
    {'parent_org': 'DG-Lab', 'shortname': 'MAL', 'fullname': 'Material Analysis Lab', 'chinesename': '材料分析实验室'},
    {'parent_org': 'MTS', 'shortname': 'PDS', 'fullname': 'Process Design Simulation',
     'chinesename': '电芯工艺仿真组　'},
    {'parent_org': 'MTS', 'shortname': 'CDS', 'fullname': 'Cell Design Simulation', 'chinesename': '电芯产品仿真组'},
    {'parent_org': '00:01Lab', 'shortname': 'ATR', 'fullname': 'Advanced Technology Radar',
     'chinesename': '先进技术雷达组'},
    {'parent_org': '00:01Lab', 'shortname': 'ATI', 'fullname': 'Advanced Technology Incubator',
     'chinesename': '先进技术孵化组'},
    {'parent_org': 'RCM', 'shortname': 'MTL', 'fullname': 'Material Testing lab', 'chinesename': '材料测试实验室'},
    {'parent_org': 'FIT', 'shortname': 'PIT', 'fullname': 'Platform Innovation Team', 'chinesename': '化学平台创新组'},
    {'parent_org': 'FIT', 'shortname': 'SIT', 'fullname': 'Synergy innovation team', 'chinesename': '协同创新组'},
    {'parent_org': 'FIT', 'shortname': 'AET', 'fullname': 'Anode Engineering Team', 'chinesename': '阳极极片工程组'},
    {'parent_org': 'FIT', 'shortname': 'CET', 'fullname': 'Cathode Engineering Team', 'chinesename': '阴极极片工程组'},
    {'parent_org': 'FIT', 'shortname': 'SET', 'fullname': 'Separator Engineering Team', 'chinesename': '隔离膜工程组'},
    {'parent_org': 'AIT', 'shortname': 'AHI', 'fullname': 'Architectural High-effect Innovation',
     'chinesename': '结构高效创新组'},
    {'parent_org': 'AIT', 'shortname': 'AEI', 'fullname': 'Architectural Economic Innovation',
     'chinesename': '结构精益创新组'},
    {'parent_org': 'AIT', 'shortname': 'API', 'fullname': 'Architectural Products Innovation',
     'chinesename': '结构产品创新组'},
    {'parent_org': 'PRJ-DG', 'shortname': 'PRJ-DG1', 'fullname': 'PAP&HUA&EA Team', 'chinesename': 'PAP&HUA&欧美组'},
    {'parent_org': 'PRJ-DG', 'shortname': 'PRJ-DG2', 'fullname': 'MIX&LEN&DO1 Team', 'chinesename': 'MIX&LEN&国内1组'},
    {'parent_org': 'PRJ-DG', 'shortname': 'PRJ-DG3', 'fullname': 'EP&SSE&CIP&DO2 Team',
     'chinesename': 'EP&SSE&国内2组'},
    {'parent_org': 'PRJ-NDPAP', 'shortname': 'PAP Phone', 'fullname': 'PAP Phone Team', 'chinesename': 'PAP Phone组'},
    {'parent_org': 'PRJ-NDPAP', 'shortname': 'PAP NB&PAD', 'fullname': 'PAP NB&PAD&MTO&FCK Team',
     'chinesename': 'PAP NB&PAD组'},
    {'parent_org': 'PRJ-NDPAP', 'shortname': 'Mini cell', 'fullname': 'Mini cell组', 'chinesename': 'Mini cell组'},
    {'parent_org': 'PRJ-NDSAP1', 'shortname': 'HUA&LEN', 'fullname': 'HUA&LEN Team', 'chinesename': 'HUA&LEN组'},
    {'parent_org': 'PRJ-NDSAP1', 'shortname': 'CC&USC', 'fullname': 'CC&USC Team', 'chinesename': 'CC&USC组'},
    {'parent_org': 'PRJ-NDSAP1', 'shortname': 'OPO&BBK', 'fullname': 'OPO&BBK Team', 'chinesename': 'OPO&BBK组'},
    {'parent_org': 'PRJ-NDSAP1', 'shortname': 'HOR&APAA', 'fullname': 'HOR&APAA Team', 'chinesename': 'HOR&APAA组'},
    {'parent_org': 'PRJ-NDSAP2', 'shortname': 'SSE&ODM', 'fullname': 'SSE&ODM Team', 'chinesename': 'SSE&ODM组'},
    {'parent_org': 'PRJ-NDSAP2', 'shortname': 'MIX&SFC&others', 'fullname': 'MIX &SFC& 国内others&日系 Team',
     'chinesename': 'MIX &SFC&others组'},
    {'parent_org': 'PRJ-NDSAP2', 'shortname': 'MET', 'fullname': 'Manufacture Engineering Team',
     'chinesename': '五新与NPI可制造性工程组'},
    {'parent_org': 'MIC', 'shortname': 'EET', 'fullname': 'Electrode Engineering Team', 'chinesename': '极片工程组'},
    {'parent_org': 'MIC', 'shortname': 'CET', 'fullname': 'Cell Engineering Team', 'chinesename': '电芯工程组'},
    {'parent_org': 'MIC', 'shortname': 'PCC', 'fullname': 'Project & Process Control Center',
     'chinesename': '产品与工艺控制部'},
    {'parent_org': 'SSL-PRD', 'shortname': 'SSL-PRD-ASSY1', 'fullname': '', 'chinesename': '装配1生产部'},
    {'parent_org': 'SSL-PRD', 'shortname': 'SSL-PRD-ASSY2', 'fullname': '', 'chinesename': '装配2生产部'},
    {'parent_org': 'SSL-PRD', 'shortname': 'SSL-PRD-MC', 'fullname': '', 'chinesename': 'SSL管理中心'},
    {'parent_org': 'SSL-ME', 'shortname': 'SSL-ME-EP', 'fullname': '', 'chinesename': '前工序设备技术部'},
    {'parent_org': 'SSL-ME', 'shortname': 'SSL-ME-ASSY1', 'fullname': '', 'chinesename': '装配1设备技术部'},
    {'parent_org': 'SSL-ME', 'shortname': 'SSL-ME-ASSY2', 'fullname': '', 'chinesename': '装配2设备技术部'},
    {'parent_org': 'SSL-PTO/EP', 'shortname': 'SSL-PRD-EP', 'fullname': '', 'chinesename': 'SSL前工序生产部'},
    {'parent_org': 'SSL-PTO/EP', 'shortname': 'SSL-PTO-PRD', 'fullname': '', 'chinesename': '样品生产部'},
    {'parent_org': 'SSL-PTO/EP', 'shortname': 'SSL-PTO-ME', 'fullname': '', 'chinesename': '样品设备技术部'},
    {'parent_org': 'MU Plus Operation', 'shortname': 'MU Plus-EP-PRD',
     'fullname': 'Manufacturing Unit Plus Electrode Production Department', 'chinesename': '智能制造特区前工序生产部'},
    {'parent_org': 'MU Plus Operation', 'shortname': 'MU Plus-ASSY-PRD',
     'fullname': 'Manufacturing Unit Plus Assembly Production Department', 'chinesename': '智能制造特区后工序生产部'},
    {'parent_org': 'MU Plus Operation', 'shortname': 'MU Plus-EP-ME',
     'fullname': 'Manufacturing Unit Plus Electrode ProductionMaintenance Engineering',
     'chinesename': '智能制造特区前工序设备部'},
    {'parent_org': 'MU Plus Operation', 'shortname': 'MU Plus-ASSY-ME',
     'fullname': 'Manufacturing Unit Plus Assembly Maintenance Engineering', 'chinesename': '智能制造特区后工序设备部'},
    {'parent_org': 'MU Plus Digi-Lean', 'shortname': 'MU Plus-EP-Digi-Lean',
     'fullname': 'Manufacturing Unit  Plus Electrode Production Digital Lean',
     'chinesename': '智能制造特区前工序Digi-Lean组'},
    {'parent_org': 'MU Plus Digi-Lean', 'shortname': 'MU Plus-ASSY-Digi-Lean',
     'fullname': 'Manufacturing Unit PlusAssembly Digital Lean', 'chinesename': '智能制造特区后工序Digi-Lean组'},
    {'parent_org': 'MU Plus Digi-Lean', 'shortname': 'MU Plus Digi-Lean PMO',
     'fullname': 'Manufacturing Unit  PlusDigital Lean Project Management Office',
     'chinesename': 'Digi-Lean项目管理办公室'},
    {'parent_org': 'PRD-ND1', 'shortname': 'EP-M', 'fullname': 'EP-M', 'chinesename': 'M区前工序'},
    {'parent_org': 'PRD-ND1', 'shortname': 'M2', 'fullname': 'M2(PAP&MIX&LEN)', 'chinesename': 'M2-PAP&MIX&LEN组'},
    {'parent_org': 'PRD-ND1', 'shortname': 'M4', 'fullname': 'M4(HUA&HOR&CC)', 'chinesename': 'M4-HUA&HOR&CC组'},
    {'parent_org': 'PRD-ND1', 'shortname': 'M5', 'fullname': 'M5(SSE&GLE&BBK)', 'chinesename': 'M5-SSE&GLE&BBK组'},
    {'parent_org': 'PRD-ND1', 'shortname': 'M3', 'fullname': 'M3(OPO&AUS&SFC)', 'chinesename': 'M3-OPO&AUS&SFC组'},
    {'parent_org': 'PRD-ND1', 'shortname': 'BCU-PRD', 'fullname': 'Battery Component Unit - Production',
     'chinesename': '电芯元件事业生产部'},
    {'parent_org': 'PRD-ND2', 'shortname': 'E7-PAP', 'fullname': 'E7-PAP', 'chinesename': 'E7-PAP组'},
    {'parent_org': 'PRD-ND2', 'shortname': 'EP-E', 'fullname': 'EP-E', 'chinesename': 'E区前工序'},
    {'parent_org': 'PRD-ND2', 'shortname': 'EP-W', 'fullname': 'EP-W', 'chinesename': 'W区前工序'},
    {'parent_org': 'PRD-ND2', 'shortname': 'W1-PAP', 'fullname': 'W1-PAP', 'chinesename': 'W1-PAP组'},
    {'parent_org': 'PRD-ND2', 'shortname': 'W2-Mini', 'fullname': 'W2-Mini', 'chinesename': 'W2-Mini组'},
    {'parent_org': 'PRD-ND2', 'shortname': 'W3-ASC', 'fullname': 'W3-ASC', 'chinesename': 'W3-ASC组'},
    {'parent_org': 'ME-EP', 'shortname': 'ME-Coating', 'fullname': 'ME-Coating', 'chinesename': '涂布段'},
    {'parent_org': 'ME-EP', 'shortname': 'ME-Slitting', 'fullname': 'ME-Slitting', 'chinesename': '备料段'},
    {'parent_org': 'ME-EP', 'shortname': 'ME-Separator', 'fullname': 'ME-Separator', 'chinesename': '隔离膜段'},
    {'parent_org': 'ME-ND1', 'shortname': 'ME-ASSY1', 'fullname': 'ME-ASSY1', 'chinesename': '装配一'},
    {'parent_org': 'ME-ND1', 'shortname': 'ME-ASSY2', 'fullname': 'ME-ASSY2', 'chinesename': '装配二'},
    {'parent_org': 'ME-ND1', 'shortname': 'ME-CC', 'fullname': 'ME-Coil Cell', 'chinesename': 'CC制造工程部'},
    {'parent_org': 'ME-ND1', 'shortname': 'ME-GC', 'fullname': 'ME-GC', 'chinesename': '目检段'},
    {'parent_org': 'ME-ND1', 'shortname': 'ME-SMED', 'fullname': 'ME-SMED', 'chinesename': 'SMED组'},
    {'parent_org': 'ME-ND2', 'shortname': 'ME-ASC', 'fullname': 'ME-ASC', 'chinesename': 'ASC组'},
    {'parent_org': 'ME-ND2', 'shortname': 'ME-TSC', 'fullname': 'ME-TSC', 'chinesename': 'TSC制造工程部'},
    {'parent_org': 'ME-ND2', 'shortname': 'ME-Mini', 'fullname': 'ME-Mini', 'chinesename': 'Mini组'},
    {'parent_org': 'ME-ND2', 'shortname': 'ME-BCU', 'fullname': 'ME-BCU', 'chinesename': 'BCU制造工程部'},
    {'parent_org': 'ME-ND2', 'shortname': 'ME-General', 'fullname': 'ME-General', 'chinesename': '公共组'},
    {'parent_org': 'ME-TC', 'shortname': 'ME-Program', 'fullname': 'ME-Program', 'chinesename': '程序组'},
    {'parent_org': 'PMC-MPS', 'shortname': 'MPS-MST', 'fullname': 'Master Plan', 'chinesename': '主计划组'},
    {'parent_org': 'PMC-MPS', 'shortname': 'MPS-SYS', 'fullname': 'System Supporting', 'chinesename': '系统支持组'},
    {'parent_org': 'PMC-PC', 'shortname': 'PC-ND', 'fullname': 'ND Plan Control', 'chinesename': '宁德计划控制组'},
    {'parent_org': 'PMC-PC', 'shortname': 'PC-SSL', 'fullname': 'SSL Plan Control', 'chinesename': '松山湖计划控制组'},
    {'parent_org': 'RP', 'shortname': 'RP-ROC', 'fullname': 'RP-Resource Operation Center',
     'chinesename': '资源运营中心'},
    {'parent_org': 'RP', 'shortname': 'RP-ND', 'fullname': 'RP-ND', 'chinesename': 'ND后工序规划与支持组'},
    {'parent_org': 'RP', 'shortname': 'RP-SSL', 'fullname': 'RP-SSL', 'chinesename': 'SSL规划与支持组'},
    {'parent_org': 'LOG-DG', 'shortname': 'LOG-DG-WH', 'fullname': 'Warehouse of Dongguan Logistics Department',
     'chinesename': '东莞物流部仓储组'},
    {'parent_org': 'LOG-DG', 'shortname': 'LOG-DG-CU', 'fullname': 'Customs of Dongguan Logistics Department',
     'chinesename': '东莞物流部关务组'},
    {'parent_org': 'LOG-ND', 'shortname': 'LOG-ND-WH', 'fullname': 'Warehouse of Ningde Logistics Department',
     'chinesename': '宁德物流部仓储组'},
    {'parent_org': 'LOG-ND', 'shortname': 'LOG-ND-CU', 'fullname': 'Customs of Ningde Logistics Department',
     'chinesename': '宁德物流部关务组'},
    {'parent_org': 'DMP', 'shortname': 'CP1', 'fullname': 'Category Procurement Department 1',
     'chinesename': '品类采购1部'},
    {'parent_org': 'DMP', 'shortname': 'CP2', 'fullname': 'Category Procurement Department 2',
     'chinesename': '品类采购2部'},
    {'parent_org': 'DMP', 'shortname': 'MC', 'fullname': 'Material Control', 'chinesename': '直接生产物料管控组'},
    {'parent_org': 'DMP', 'shortname': 'Costing&D.A', 'fullname': 'Costing&Data Analysis', 'chinesename': '成本组'},
    {'parent_org': 'NPP', 'shortname': 'EQ', 'fullname': 'Equipment', 'chinesename': '设备采购组'},
    {'parent_org': 'NPP', 'shortname': 'MRO', 'fullname': 'Maintenance Repair Operations',
     'chinesename': '运营辅助采购组'},
    {'parent_org': 'NPP', 'shortname': 'NFP/EI/Scrap', 'fullname': 'New Facility Project/Engineering/Scrap',
     'chinesename': '工程类物料采购组'},
    {'parent_org': 'PCO', 'shortname': 'System', 'fullname': 'System', 'chinesename': '系统组'},
    {'parent_org': 'SQM', 'shortname': 'SQE', 'fullname': '', 'chinesename': '供应商质量工程组'},
    {'parent_org': 'SQM', 'shortname': 'IQC-DG', 'fullname': '', 'chinesename': '来料质量管控-DG组'},
    {'parent_org': 'SQM', 'shortname': 'IQC-ND', 'fullname': '', 'chinesename': '来料质量管控-ND组'},
    {'parent_org': 'SQM', 'shortname': 'IQC-BCU', 'fullname': 'Incoming Quality Contral-Battery Component Unit',
     'chinesename': '来料质量管控-BCU组'},
    {'parent_org': 'QE', 'shortname': 'ICT-Domestic', 'fullname': 'ICT-Domestic', 'chinesename': 'ICT国内客户组'},
    {'parent_org': 'QE', 'shortname': 'ICT-J&K', 'fullname': 'Japan&Korea', 'chinesename': '日韩组'},
    {'parent_org': 'QE', 'shortname': 'ICT-Overseas', 'fullname': 'ICT-Overseas', 'chinesename': 'ICT国外客户组'},
    {'parent_org': 'QE', 'shortname': 'PH', 'fullname': 'Pack house', 'chinesename': '驻厂组'},
    {'parent_org': 'QE', 'shortname': 'TQE', 'fullname': 'Technology Quality Engineering',
     'chinesename': '技术品质工程组'},
    {'parent_org': 'QMC', 'shortname': 'QMS', 'fullname': 'Quality Management System', 'chinesename': '质量管理体系组'},
    {'parent_org': 'QMC', 'shortname': 'FQC/OQC', 'fullname': 'Final Quality Control/Outgoing Quality Control',
     'chinesename': '最终/出货质量控制组'},
    {'parent_org': 'QMC', 'shortname': 'FQC/OQC-PTO',
     'fullname': 'Final Quality Control/Outgoing Quality Control-Prototype', 'chinesename': '最终/出货质量控制-制样组'},
    {'parent_org': 'QMC', 'shortname': 'IPQC', 'fullname': 'In Process Quality Control',
     'chinesename': '制程质量控制组'},
    {'parent_org': 'QMC', 'shortname': 'IPQC-PTO', 'fullname': 'In Process Quality Control-Prototype',
     'chinesename': '制程质量控制-制样组'},
    {'parent_org': 'FOM', 'shortname': 'M', 'fullname': 'Manufacturing Zone', 'chinesename': 'M区运维组'},
    {'parent_org': 'FOM', 'shortname': 'E&R', 'fullname': 'East zone & Research Institute zone',
     'chinesename': 'E&R区运维组'},
    {'parent_org': 'FOM', 'shortname': 'W', 'fullname': 'West zone', 'chinesename': 'W区运维组'},
    {'parent_org': 'FOM', 'shortname': 'SSL', 'fullname': 'Songshan Lake', 'chinesename': 'SSL区运维组'},
    {'parent_org': 'SYS', 'shortname': 'SS', 'fullname': 'System Support', 'chinesename': '系统支持组'},
    {'parent_org': 'SYS', 'shortname': 'EMC', 'fullname': 'Energy Management Center', 'chinesename': '能源管理中心'},
    {'parent_org': 'Tech', 'shortname': 'TSE', 'fullname': 'Technology Support and Execute management',
     'chinesename': '技术支持与执行组'},
    {'parent_org': 'Tech', 'shortname': 'OSPE1', 'fullname': 'Overseas Project Engineering1',
     'chinesename': '印度厂房筹建组'},
    {'parent_org': 'EHS-DG', 'shortname': 'Site-SSL', 'fullname': 'Environment,Health and Safety  Site Management',
     'chinesename': 'SSL EHS现场管理组'},
    {'parent_org': 'EHS-ND', 'shortname': 'Site-M&E', 'fullname': 'Environment,Health and Safety  Site Management(M&E)',
     'chinesename': '湖东现场管理组'},
    {'parent_org': 'EHS-ND', 'shortname': 'Site-W', 'fullname': 'Environment,Health and Safety  Site Management(W)',
     'chinesename': '湖西现场管理组'},
    {'parent_org': 'EHS-ND', 'shortname': 'Site-R&PTO',
     'fullname': 'Environment,Health and Safety  Site Management(Research Institute&PTO)',
     'chinesename': '研究院&PTO现场管理组'}
]


if __name__ == '__main__':
    departments = first_departments + second_departments + third_departments
    def get_node_info(nodename):

        shortnames = [a['shortname'].lower().replace(' ','') for a in departments]

        # print(shortnames)
        # if nodename.lower() in shortnames:
        try:
            current_node = departments[shortnames.index(nodename.lower())]
        except:
            return {'status':'error','content':"这个部门不在公司的现有编制里面，请确认"}
        parent_nodes = [current_node]
        node_temp = current_node.copy()

        for i in range(2):
            if node_temp['parent_org'] !='':
                parent_node = departments[shortnames.index(node_temp['parent_org'].lower())]
                parent_nodes.append(parent_node)
                node_temp = parent_node.copy()
            else:continue
        if len(parent_nodes)==3:
            res = {
                'parent_org':parent_nodes[2],
                'current_org':parent_nodes[1],
                'son_org':parent_nodes[0],
            }
        elif len(parent_nodes)==2:
            res = {
                'parent_org':parent_nodes[1],
                'current_org':parent_nodes[0],
                'son_org':'',
            }
        elif len(parent_nodes)==1:
            res = {
                'parent_org':parent_nodes[0],
                'current_org':'',
                'son_org':'',
            }
        return res

    def to_markdown():


        for ii, i in enumerate(first_departments):
            markdown_temp = '''
|\t机构层级\t|\t父级机构\t|\t简称\t|\t全称\t|\t中文名称\t|
|---------|---------|------|------|--------|
'''
            first_text = f'''|\t一级机构\t|\t-\t|\t{i['shortname']}\t|\t{i['fullname']}\t|\t{i['chinesename']}\t|\n'''
            markdown_temp +=first_text
            for s in second_departments:
                if s['parent_org'] == i['shortname']:
                    second_text = f'''|\t二级机构\t|\t{s['parent_org']}\t|\t{s['shortname']}\t|\t{s['fullname']}\t|\t{s['chinesename']}\t|\n'''

                    markdown_temp += second_text
                    for t in third_departments:
                        # if t['parent_org'] == s['shortname'] :
                        if t['parent_org'] == s['shortname'] and s['parent_org'] == i['shortname']:
                            third_text = f'''|\t三级机构\t|\t{t['parent_org']}\t|\t{t['shortname']}\t|\t{t['fullname']}\t|\t{t['chinesename']}\t|\n'''

                            markdown_temp += third_text
            print(len(markdown_temp))
            with open(f'/datas/liab/DB-GPT/tests/atl_data/type2/new_department/{ii}.md','w',encoding='utf-8') as f:
                f.write(markdown_temp.strip())
    to_markdown()