FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

RUN apt-get update && apt-get install -y \
	git \
	python3 \
	pip

	
WORKDIR /app

COPY . /app


# upgrade pip
RUN pip3 install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 7860

CMD ["python3", "pilot/server/webserver.py"]
