[project]
name = "dbgpt-sandbox"
version = "0.7.3"
description = "A secure sandbox execution environment for DB-GPT Agent"
authors = [
    { name = "csunny", email = "cfqcsunny@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
    "psutil>=5.9.0",
    "colorama>=0.4.4",
    "docker>=6.0.0",
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "pydantic>=1.8.0",
    "python-multipart>=0.0.5",
    "selenium>=4.0.0",
    "typing-extensions>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/eosphoros-ai/DB-GPT"
Documentation = "http://docs.dbgpt.cn/docs/overview"
Repository = "https://github.com/eosphoros-ai/DB-GPT.git"
Issues = "https://github.com/eosphoros-ai/DB-GPT/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-asyncio>=0.18.0",
    "black>=22.0",
    "flake8>=4.0",
]

[tool.uv]
managed = true
dev-dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/dbgpt_sandbox"]
exclude = [
    "src/dbgpt_sandbox/**/tests",
    "src/dbgpt_sandbox/**/tests/*",
    "src/dbgpt_sandbox/tests",
    "src/dbgpt_sandbox/tests/*",
    "src/dbgpt_sandbox/**/examples",
    "src/dbgpt_sandbox/**/examples/*"
]

[project.scripts]
dbgpt-sandbox = "dbgpt_sandbox.sandbox.main:main"