-- From 0.8.0 to 0.8.1, we have the following changes:
USE dbgpt;

-- connector_instance, Persist MCP connector instances (encrypted credentials, transport/extra config, lifecycle status)
CREATE TABLE IF NOT EXISTS `connector_instance` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Auto increment id',
  `connector_id` varchar(64) NOT NULL COMMENT 'Connector UUID',
  `connector_type` varchar(64) NOT NULL COMMENT 'Connector type, e.g. yuque, feishu, custom_mcp',
  `display_name` varchar(256) DEFAULT NULL COMMENT 'Display name',
  `encrypted_credentials` text COMMENT 'Encrypted credentials JSON',
  `encryption_salt` varchar(256) DEFAULT NULL COMMENT 'Encryption salt',
  `status` varchar(32) DEFAULT NULL COMMENT 'Status: active / error / disconnected / needs_reactivation',
  `config_json` text COMMENT 'Extra config JSON (server_uri, transport, description, auth_type, header_name, ...)',
  `user_name` varchar(128) DEFAULT NULL COMMENT 'User name',
  `sys_code` varchar(128) DEFAULT NULL COMMENT 'System code',
  `gmt_created` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation time',
  `gmt_modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_connector_instance_connector_id` (`connector_id`),
  KEY `ix_connector_instance_user_name` (`user_name`),
  KEY `ix_connector_instance_sys_code` (`sys_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MCP connector instance table';

-- dbgpt_serve_scheduled_task, Scheduled task definitions (cron-based chat replay tasks)
CREATE TABLE IF NOT EXISTS `dbgpt_serve_scheduled_task` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Auto increment id',
  `task_id` varchar(64) NOT NULL COMMENT 'Task UUID',
  `task_name` varchar(256) NOT NULL COMMENT 'Task name',
  `description` text DEFAULT NULL COMMENT 'Task description',
  `task_type` varchar(32) NOT NULL DEFAULT 'chat_replay' COMMENT 'Task type, e.g. chat_replay',
  `cron_expression` varchar(128) NOT NULL COMMENT 'Cron expression for scheduling',
  `payload_json` text NOT NULL COMMENT 'Frozen conversation snapshot JSON',
  `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Whether the task is enabled, 1: enabled, 0: disabled',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation time',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update time',
  `user_name` varchar(128) DEFAULT NULL COMMENT 'User name',
  `sys_code` varchar(128) DEFAULT NULL COMMENT 'System code',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheduled_task_task_id` (`task_id`),
  KEY `ix_scheduled_task_task_type` (`task_type`),
  KEY `ix_scheduled_task_user_name` (`user_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Scheduled task definition table';

-- dbgpt_serve_scheduled_run, Scheduled task execution history (run records for each task trigger)
CREATE TABLE IF NOT EXISTS `dbgpt_serve_scheduled_run` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Auto increment id',
  `run_id` varchar(64) NOT NULL COMMENT 'Run UUID',
  `task_id` varchar(64) NOT NULL COMMENT 'Associated task UUID',
  `started_at` datetime NOT NULL COMMENT 'Run start time',
  `finished_at` datetime DEFAULT NULL COMMENT 'Run finish time',
  `status` varchar(32) NOT NULL COMMENT 'Run status: running / success / failed / timeout',
  `result_summary` text DEFAULT NULL COMMENT 'Result summary',
  `error_message` text DEFAULT NULL COMMENT 'Error message if failed',
  `output_conv_uid` varchar(64) DEFAULT NULL COMMENT 'Output conversation UID generated by this run',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheduled_run_run_id` (`run_id`),
  KEY `ix_scheduled_run_task_id` (`task_id`),
  KEY `ix_scheduled_run_started_at` (`started_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Scheduled task execution history table';
